/**
 * lesson.js - one lesson from a club's practice tree.
 *
 * Three steps, and a player can jump between them in any order:
 *
 *   Instructions  the lesson in words (marked read once opened)
 *   Watch         the animated demonstration: frames with arrows and marks,
 *                 stepped by hand or played back automatically
 *   Challenges    the positions to solve, one at a time
 *
 * All of it is data (js/data/lessons.js, generated by tools/build-lessons.mjs
 * from Gambit Academy's verified content). A challenge's candidate moves were
 * judged at build time, so this screen looks a move up rather than grading it:
 * no engine is needed and nothing here can contradict the verification.
 */

import { h, button, wait } from '../dom.js';
import { pixelIcon } from '../icons.js';
import { sfx } from '../audio.js';
import { createBoard } from '../board.js';
import { createRules } from '../../chess/core/rules.js';
import { HIGHLIGHT, ARROW } from '../../chess/render/boardRenderer.js';
import { lessonById } from '../../data/lessons.js';
import { tierForBand, lessonProgress, markRead, markWatched, recordChallengeSolved, settleLesson } from '../../core/lessons.js';

const BRANCH_ICON = {
  fundamentals: 'pawn', vision: 'hint', tactics: 'xp', calculation: 'practice', checkmates: 'side-white',
  openings: 'journal', strategy: 'map', pawns: 'pawn', endgames: 'trophy', defense: 'side-black',
  practical: 'club', analysis: 'practice'
};
const bandLabel = (band) => (band === 0 ? 'Start' : String(band));

/** replaceChildren() turns a null into the text "null"; h() drops it. */
const fill = (host, ...kids) => host.replaceChildren(...kids.flat().filter(Boolean));

/** Only <b>, <i>, <em> and <strong> survive: the text is ours, but it goes
    through innerHTML, so it is filtered anyway. */
export function richText(text) {
  const escaped = String(text || '')
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  return escaped.replace(/&lt;(\/?)(b|i|em|strong)&gt;/g, '<$1$2>');
}

/** 'e4' and '4e' are the classic beginner slip; say so when it happens. */
const swapped = (square, target) => square.length === 2 && target.length === 2
  && square[0] === target[1] && square[1] === target[0];

export function lessonScreen(app, params) {
  const career = app.career;
  const lesson = lessonById(params.lessonId);
  if (!lesson) { app.toast('That lesson does not exist.'); app.go('practice', params); return { el: h('div') }; }
  const tier = tierForBand(lesson.band);
  const backToTree = () => app.go('practice', { clubId: params.clubId, returnScene: params.returnScene, lessonId: lesson.id });

  let step = params.step === 'watch' || params.step === 'solve' ? params.step : 'read';
  let frame = 0;
  let autoplay = null;
  let index = Math.max(0, lesson.challenges.findIndex((c) => !career.lessons?.[lesson.id]?.solved?.[c.id]));
  if (index < 0 || index >= lesson.challenges.length) index = 0;
  let rules = null;
  let locked = false;
  let hintLevel = 0;
  let solvedNow = false;
  let unwireSelect = null;

  const challenge = () => lesson.challenges[index];
  const isSolved = (c) => !!career.lessons?.[lesson.id]?.solved?.[c.id];

  /* ------------------------------------------------------------- the board */
  const board = createBoard(app, {
    orientation: lesson.demo[0]?.orientation || challenge().orientation,
    getFen: () => (rules ? rules.fen() : (lesson.demo[frame]?.fen || challenge().fen)),
    getDestinations: (square) => {
      if (step !== 'solve' || locked || !rules || challenge().kind !== 'move') return [];
      return rules.moves({ square, verbose: true }).map((m) => ({ to: m.to, capture: !!m.captured, promotion: !!m.promotion }));
    },
    getMovableColour: () => (step === 'solve' && !locked && rules && challenge().kind === 'move' ? challenge().sideToMove : null),
    onMove: (move) => attemptMove(move)
  });
  const { renderer } = board;

  /* -------------------------------------------------------------- the panel */
  const title = h('div.pp-h2', { text: lesson.title });
  const subtitle = h('div.pp-small.pp-muted');
  const tabs = h('div.pp-row.pp-lesson__tabs');
  const body = h('div.pp-lesson__body');
  const actions = h('div.pp-row.pp-lesson__actions');
  const progressLine = h('div.pp-small.pp-muted');
  const panel = h('aside.pp-match__left', null,
    h('div.pp-panel.pp-col.pp-lesson__panel', null,
      h('div', null, title, subtitle),
      tabs,
      body,
      progressLine,
      actions));
  const el = h('div.pp-screen.pp-lesson', null,
    app.hud({ where: tier ? `${tier.label} · ${bandLabel(lesson.band)}` : 'Practice' }),
    h('div.pp-match.pp-match--lesson', null, panel, h('main.pp-match__board', null, board.frame), h('aside.pp-match__right')));

  /* ------------------------------------------------------------------ paint */
  function paintTabs() {
    const p = lessonProgress(career, lesson);
    const tab = (id, icon, label, done, note) => h('button.pp-lesson__tab', {
      type: 'button', class: `${step === id ? 'is-active' : ''} ${done ? 'is-done' : ''}`,
      onclick: () => setStep(id)
    }, h('b', null, pixelIcon(icon, { size: 'sm' }), h('span', { text: ` ${label}` })), h('span.pp-small', { text: note }));
    fill(tabs,
      tab('read', 'journal', 'Instructions', p.read, p.read ? 'read' : 'unread'),
      lesson.demo.length ? tab('watch', 'play', 'Watch', p.watched, p.watched ? 'watched' : `${lesson.demo.length} frames`) : null,
      tab('solve', 'practice', 'Challenges', p.solved >= p.total, `${p.solved}/${p.total} solved`)
    );
    progressLine.textContent = p.complete
      ? 'Lesson complete. Everything here stays open: replay it whenever you like.'
      : `${p.read ? 'Read' : 'Not read'} · ${lesson.demo.length ? (p.watched ? 'watched' : 'not watched') : 'no demo'} · ${p.solved}/${p.total} challenges solved.`;
  }

  function setStep(next) {
    stopAuto();
    step = next;
    hintLevel = 0;
    solvedNow = false;
    unwireSelect?.();
    unwireSelect = null;
    if (step === 'read') paintRead();
    if (step === 'watch') { frame = 0; paintWatch(); }
    if (step === 'solve') loadChallenge(index);
    paintTabs();
  }

  /* ------------------------------------------------------------ 1. read */
  function paintRead() {
    rules = null;
    board.input.setEnabled(false);
    const shown = lesson.demo[0] || challenge();
    renderer.setOrientation(shown.orientation || 'w');
    renderer.clearArrows(); renderer.clearHighlights(); renderer.clearVerdicts();
    renderer.render(shown.fen);
    if (lesson.demo[0]?.marks) markSquares(lesson.demo[0].marks);
    const first = markRead(career, lesson.id);
    const settled = settleLesson(career, lesson.id);
    if (first || settled.lessonComplete) app.save();
    if (settled.lessonComplete) celebrate(settled.lessonXp);
    fill(body,
      h('p.pp-lesson__text', { html: richText(lesson.instructions) }),
      h('p.pp-small.pp-muted', { text: lesson.demo.length
        ? 'Next: watch it happen on the board, then try the challenges. You can do them in any order.'
        : 'Next: try the challenges. You can come back to this page any time.' }));
    fill(actions,
      lesson.demo.length
        ? button('Watch it', () => setStep('watch'), { cls: 'pp-btn--gold', icon: pixelIcon('play', { size: 'sm' }) })
        : button('Challenges', () => setStep('solve'), { cls: 'pp-btn--gold', icon: pixelIcon('practice', { size: 'sm' }) }),
      button('Back to the tree', backToTree, { cls: 'pp-btn--small' }));
  }

  /* ----------------------------------------------------------- 2. watch */
  function markSquares(marks) {
    Object.entries(marks || {}).forEach(([square, kind]) => {
      const map = { best: HIGHLIGHT.BEST, hint: HIGHLIGHT.HINT, threat: HIGHLIGHT.THREAT };
      renderer.highlightSquare(square, map[kind] || HIGHLIGHT.BEST);
    });
  }

  function paintWatch(animate = false) {
    rules = null;
    board.input.setEnabled(false);
    const f = lesson.demo[frame];
    if (f.orientation) renderer.setOrientation(f.orientation);
    renderer.clearArrows(); renderer.clearHighlights(); renderer.clearVerdicts();
    renderer.render(f.fen, { move: animate && f.move ? { from: f.move.from, to: f.move.to } : null });
    if (f.move) renderer.highlightMove({ from: f.move.from, to: f.move.to }, HIGHLIGHT.LAST_MOVE);
    markSquares(f.marks);
    (f.arrows || []).forEach((a) => {
      const kind = { threat: ARROW.THREAT, book: ARROW.BOOK, hint: ARROW.HINT }[a.kind] || ARROW.HINT;
      renderer.drawArrow({ from: a.from, to: a.to }, kind);
    });
    const last = frame >= lesson.demo.length - 1;
    fill(body,
      h('div.pp-lesson__frame', null,
        h('div.pp-small.pp-muted', { text: `Frame ${frame + 1} of ${lesson.demo.length}${f.move ? ` · ${f.move.san}` : ''}` }),
        h('p.pp-lesson__text', { html: richText(f.text || (f.move ? f.move.san : '')) })),
      h('div.pp-dots', null, lesson.demo.map((_, i) => h('span.pp-dot', { class: i === frame ? 'is-current' : (i < frame ? 'is-done' : '') }))));
    fill(actions,
      button('Back', () => goFrame(frame - 1), { cls: 'pp-btn--small', title: 'Previous frame', icon: pixelIcon('back', { size: 'sm' }) }),
      button(autoplay ? 'Pause' : 'Play', () => toggleAuto(), { cls: 'pp-btn--small pp-btn--blue', icon: pixelIcon('play', { size: 'sm' }) }),
      last
        ? button('Challenges', () => setStep('solve'), { cls: 'pp-btn--gold', icon: pixelIcon('practice', { size: 'sm' }) })
        : button('Next', () => goFrame(frame + 1), { cls: 'pp-btn--gold', icon: pixelIcon('play', { size: 'sm' }) }),
      button('Instructions', () => setStep('read'), { cls: 'pp-btn--small' }),
      button('Tree', backToTree, { cls: 'pp-btn--small' }));
    if (last) finishWatching();
  }

  function goFrame(next) {
    const target = Math.max(0, Math.min(lesson.demo.length - 1, next));
    if (target === frame) { if (target === frame && next > frame) stopAuto(); return; }
    const forward = target === frame + 1;
    frame = target;
    if (forward) sfx.move();
    paintWatch(forward);
  }

  function finishWatching() {
    const first = markWatched(career, lesson.id);
    const settled = settleLesson(career, lesson.id);
    if (first || settled.lessonComplete) app.save();
    if (first) paintTabs();
    if (settled.lessonComplete) celebrate(settled.lessonXp);
  }

  function toggleAuto() {
    if (autoplay) { stopAuto(); paintWatch(); return; }
    if (frame >= lesson.demo.length - 1) frame = 0;
    autoplay = setInterval(() => {
      if (frame >= lesson.demo.length - 1) { stopAuto(); paintWatch(); return; }
      goFrame(frame + 1);
    }, 2100);
    paintWatch();
  }
  function stopAuto() { clearInterval(autoplay); autoplay = null; }

  /* --------------------------------------------------------- 3. challenges */
  function loadChallenge(i) {
    index = Math.max(0, Math.min(lesson.challenges.length - 1, i));
    const c = challenge();
    rules = createRules(c.fen);
    locked = false;
    hintLevel = 0;
    solvedNow = false;
    renderer.setOrientation(c.orientation);
    renderer.clearArrows(); renderer.clearHighlights(); renderer.clearVerdicts();
    renderer.render(c.fen);
    /* A square challenge still needs the board to report taps, so input stays
       on: with no destinations and no movable colour, nothing can be moved. */
    board.input.setEnabled(true);
    unwireSelect?.();
    unwireSelect = c.kind === 'square' ? renderer.onSquareSelected((square, event) => {
      if (event?.phase && event.phase !== 'down') return;
      attemptSquare(square);
    }) : null;
    paintChallenge();
  }

  const verdictLine = h('p.pp-lesson__verdict');
  const hintLine = h('p.pp-small.pp-muted');

  function paintChallenge(verdict = null, tone = '') {
    const c = challenge();
    const done = isSolved(c);
    verdictLine.textContent = verdict || '';
    verdictLine.className = `pp-lesson__verdict ${tone}`;
    fill(body,
      h('div.pp-row', { style: { justifyContent: 'space-between' } },
        h('div.pp-small.pp-muted', { text: `Challenge ${index + 1} of ${lesson.challenges.length}${c.label ? ` · ${c.label}` : ''}` }),
        h('div.pp-small', { text: done ? 'solved' : (c.kind === 'square' ? 'tap a square' : `${c.sideToMove === 'w' ? 'White' : 'Black'} to move`) })),
      h('p.pp-lesson__text', { html: richText(c.prompt) }),
      verdictLine,
      hintLine,
      h('div.pp-dots.pp-dots--many', null, lesson.challenges.map((x, i) => h('button.pp-dot', {
        type: 'button', title: x.label || `Challenge ${i + 1}`,
        class: `${isSolved(x) ? 'is-done' : ''} ${i === index ? 'is-current' : ''}`,
        onclick: () => loadChallenge(i)
      }))));
    const next = index < lesson.challenges.length - 1;
    fill(actions,
      solvedNow && next ? button('Next challenge', () => loadChallenge(index + 1), { cls: 'pp-btn--gold', icon: pixelIcon('play', { size: 'sm' }) }) : null,
      solvedNow && !next ? button('Back to the tree', backToTree, { cls: 'pp-btn--gold' }) : null,
      c.hints.length ? button('Hint', () => giveHint(), { cls: 'pp-btn--small pp-btn--blue', icon: pixelIcon('hint', { size: 'sm' }), disabled: hintLevel >= c.hints.length + 1 }) : null,
      button('Retry', () => loadChallenge(index), { cls: 'pp-btn--small', icon: pixelIcon('back', { size: 'sm' }) }),
      button('Instructions', () => setStep('read'), { cls: 'pp-btn--small' }),
      button('Tree', backToTree, { cls: 'pp-btn--small' }));
  }

  function uciOf(move, applied) {
    const promo = applied.promotion && applied.promotion !== 'q' ? applied.promotion : '';
    return applied.from + applied.to + promo;
  }

  async function attemptMove(move) {
    const c = challenge();
    if (locked || c.kind !== 'move') return;
    const probe = createRules(rules.fen());
    let applied = null;
    try { applied = probe.move({ from: move.from, to: move.to, promotion: move.promotion || undefined }); } catch { applied = null; }
    if (!applied) { sfx.illegal(); return; }
    const uci = uciOf(move, applied);
    const verdict = c.verdicts[uci];
    const correct = c.answers.includes(uci);

    if (correct) {
      rules.move({ from: applied.from, to: applied.to, promotion: applied.promotion || undefined });
      renderer.render(rules.fen(), { move: { from: applied.from, to: applied.to } });
      renderer.clearHighlights(HIGHLIGHT.HINT);
      renderer.highlightMove(applied, HIGHLIGHT.LAST_MOVE);
      locked = true;
      board.input.setEnabled(false);
      sfx.best();
      board.fx.ring(applied.to, '#36d6d6');
      solvedNow = true;
      const result = recordChallengeSolved(career, lesson.id, c.id);
      app.save();
      const text = verdict?.text || c.success || 'Correct.';
      paintChallenge(result.firstSolve && result.xp ? `${text} (+${result.xp.xp} XP)` : text, 'is-good');
      paintTabs();
      if (result.lessonComplete) celebrate(result.lessonXp);
      return;
    }

    /* A move with an authored verdict: show it, and put the position back so
       the challenge can be tried again. */
    rules.move({ from: applied.from, to: applied.to, promotion: applied.promotion || undefined });
    renderer.render(rules.fen(), { move: { from: applied.from, to: applied.to } });
    locked = true;
    sfx.mistake();
    board.fx.chip(applied.to, verdict?.outcome === 'retry' ? 'Try again' : 'No', '#ff8f3a');
    if (verdict?.outcome !== 'retry') board.fx.shake();
    paintChallenge(verdict?.text || c.fallback, 'is-bad');
    await wait(1500);
    if (step !== 'solve' || challenge() !== c) return;
    rules = createRules(c.fen);
    renderer.clearHighlights(HIGHLIGHT.LAST_MOVE);
    renderer.render(c.fen);
    locked = false;
    board.input.setEnabled(true);
  }

  function attemptSquare(square) {
    const c = challenge();
    if (locked || c.kind !== 'square') return;
    if (square === c.target) {
      locked = true;
      renderer.clearHighlights();
      renderer.highlightSquare(square, HIGHLIGHT.BEST);
      sfx.best();
      board.fx.ring(square, '#36d6d6');
      solvedNow = true;
      const result = recordChallengeSolved(career, lesson.id, c.id);
      app.save();
      paintChallenge(result.firstSolve && result.xp ? `${c.success} (+${result.xp.xp} XP)` : c.success, 'is-good');
      paintTabs();
      if (result.lessonComplete) celebrate(result.lessonXp);
      return;
    }
    renderer.clearHighlights();
    /* CHECK, not THREAT: a red glow reads as "no", while the threat marker is
       crossed swords and means "this is where they hit you". */
    renderer.highlightSquare(square, HIGHLIGHT.CHECK);
    sfx.mistake();
    board.fx.shake();
    paintChallenge(swapped(square, c.target)
      ? `Not that square. That is ${square} — you swapped the letter and the number.`
      : `Not ${square}. Read the file letter along the bottom and the rank number up the side.`, 'is-bad');
  }

  function giveHint() {
    const c = challenge();
    hintLevel += 1;
    sfx.hint();
    if (hintLevel <= c.hints.length) {
      hintLine.textContent = `Hint ${hintLevel}: ${c.hints[hintLevel - 1]}`;
      return;
    }
    /* Last resort: show it on the board. */
    if (c.kind === 'square') {
      renderer.highlightSquare(c.target, HIGHLIGHT.HINT);
      hintLine.textContent = `It is ${c.target}. Tap it to go on.`;
      return;
    }
    const answer = c.answers[0];
    renderer.highlightSquare(answer.slice(0, 2), HIGHLIGHT.HINT);
    renderer.highlightSquare(answer.slice(2, 4), HIGHLIGHT.HINT);
    renderer.drawArrow({ from: answer.slice(0, 2), to: answer.slice(2, 4) }, ARROW.HINT);
    hintLine.textContent = `The move is ${c.verdicts[answer]?.san || answer}. Play it on the board.`;
  }

  function celebrate(xp) {
    sfx.brilliant();
    board.fx.word('LESSON DONE', '#ffc341', xp ? `+${xp.xp} XP` : '');
    app.toast(`${lesson.title}: lesson complete${xp ? ` · +${xp.xp} XP` : ''}`, { ms: 3600 });
  }

  fill(subtitle,
    h('span.pp-icotext', null, pixelIcon(BRANCH_ICON[lesson.branch] || 'practice', { size: 'sm' }), h('span', { text: lesson.branch })),
    h('span', { text: ` · ${tier ? tier.label : 'Practice'} · rating band ${bandLabel(lesson.band)}` }));
  setStep(step);

  return {
    el,
    /* The handle tools/cdp_lessons.py drives: a browser test can step the demo
       and answer a challenge without simulating drags on a canvas. */
    lesson: {
      data: lesson,
      get step() { return step; },
      get frame() { return frame; },
      get index() { return index; },
      get challenge() { return challenge(); },
      setStep,
      goFrame,
      loadChallenge,
      attempt: (uci) => (challenge().kind === 'square'
        ? Promise.resolve(attemptSquare(uci))
        : attemptMove({ from: uci.slice(0, 2), to: uci.slice(2, 4), promotion: uci.slice(4) || undefined }))
    },
    destroy() {
      stopAuto();
      unwireSelect?.();
      board.destroy();
    }
  };
}

export default lessonScreen;
