#!/usr/bin/env node
/**
 * stats.mjs - js/data/openingStats.js from tree.json: for every line in
 * js/data/openings.js, how many of the researched games reached each ply of it.
 * The opening study shows it ("reached in 1,204 master games"), so the player
 * can see which lines are real-world main lines and which are rare.
 *
 *   node tools/opening-research/stats.mjs
 *
 * Counts below the tree's pruning floor are stored as null ("rare").
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { OPENINGS } from '../../js/data/openings.js';

const here = new URL('.', import.meta.url);
const data = JSON.parse(readFileSync(new URL('tree.json', here), 'utf8'));
const out = {};
for (const o of OPENINGS) {
  const tree = data.trees[o.id];
  out[o.id] = o.lines.map((line) => {
    let node = tree;
    return line.map((san) => {
      const child = node?.[san];
      node = child?.c;
      return child ? child.n : null;
    });
  });
}
const meta = { months: [data.months[0], data.months[data.months.length - 1]], minElo: data.minElo, games: data.stats.kept, roots: data.roots };
const js = `/**
 * openingStats.js - GENERATED by tools/opening-research/stats.mjs. Do not edit.
 *
 * GAMES[openingId][lineIndex][ply] = how many researched games (Lichess
 * broadcasts ${meta.months[0]}..${meta.months[1]}, both players ${meta.minElo}+) reached that move
 * of that line in exactly that move order; null = too rare to count.
 */
export const OPENING_RESEARCH = ${JSON.stringify(meta)};
export const GAMES = ${JSON.stringify(out)};
export default GAMES;
`;
writeFileSync(new URL('../../js/data/openingStats.js', here), js);
for (const o of OPENINGS) console.log(o.id, out[o.id].map((l) => l[Math.min(l.length, 12) - 1]).join(' '));
