/**
 * tools/verify-puzzles.mjs - proves every mission puzzle with Stockfish and
 * writes js/data/puzzles.js.
 *
 *   node tools/verify-puzzles.mjs
 *
 * For each player move in a seed's intended line:
 *   - the move must be legal and must be the engine's first choice (or an
 *     equally short mate),
 *   - it must be UNIQUE: no second move mates as fast, and a non-mating
 *     puzzle needs a clear 150cp margin over the runner-up while winning.
 * Opponent replies are replaced by the engine's best defence, and the line is
 * trimmed at the first player move that stops being unique. A seed whose FIRST
 * move fails is dropped and reported. Nothing is trusted from the seed file
 * except the composer's intention.
 */

import { writeFile } from 'node:fs/promises';
import { StockfishEngine } from '../js/chess/engine/stockfishEngine.js';
import { createNodeStockfishTransport } from '../tests/nodeTransport.js';
import { createRules, uciFor, applyUci, sanFor, isCheckmate } from '../js/chess/core/rules.js';
import { scoreToCp } from '../js/chess/analysis/moveClassifier.js';
import { PUZZLE_SEEDS } from './puzzle-seeds.mjs';

const DEPTH = 18;
const MARGIN = 150;

const engine = new StockfishEngine({ createTransport: createNodeStockfishTransport });
await engine.init();

function startFen(seed) {
  if (seed.fen) return seed.fen;
  const rules = createRules();
  for (const san of seed.moves) {
    if (!rules.move(san)) throw new Error(`illegal setup move ${san}`);
  }
  return rules.fen();
}

const mateIn = (score) => (typeof score?.mate === 'number' && score.mate > 0 ? score.mate : null);

const out = [];
const report = [];

for (const seed of PUZZLE_SEEDS) {
  let fen;
  try { fen = startFen(seed); } catch (error) { report.push(`DROP ${seed.id}: ${error.message}`); continue; }
  const start = fen;
  const solution = [];
  const notes = [];
  let dropped = null;

  for (let i = 0; i < seed.line.length; i += 1) {
    const playerTurn = i % 2 === 0;
    const result = await engine.analyze(fen, { depth: DEPTH, multiPv: 3 });
    const [best, second] = result.lines;
    if (!best) { dropped = 'no engine line'; break; }

    if (!playerTurn) {
      // The defence is whatever the engine would actually play.
      const intended = uciFor(fen, seed.line[i]);
      if (intended !== best.move) notes.push(`reply ${seed.line[i]} -> ${best.san}`);
      solution.push(best.move);
      fen = applyUci(fen, best.move).fen;
      continue;
    }

    const uci = uciFor(fen, seed.line[i]);
    if (!uci) { dropped = `illegal ${seed.line[i]}`; break; }
    const after = applyUci(fen, uci).fen;
    const mates = isCheckmate(after);

    let ok;
    let why;
    if (mates) {
      ok = true; why = 'mates';
    } else if (mateIn(best.score)) {
      const n = mateIn(best.score);
      const playedIsBest = best.move === uci;
      const rival = second && second.move !== uci && mateIn(second.score) && mateIn(second.score) <= n;
      ok = playedIsBest && !rival;
      why = !playedIsBest ? `engine prefers ${best.san} (M${n})` : rival ? `${second.san} also mates in ${mateIn(second.score)}` : `M${n}`;
    } else {
      const bestCp = scoreToCp(best.score);
      const secondCp = second ? scoreToCp(second.score) : bestCp - 10000;
      ok = best.move === uci && bestCp - secondCp >= MARGIN && bestCp >= MARGIN;
      why = best.move !== uci ? `engine prefers ${best.san}` : `best ${bestCp}cp, margin ${bestCp - secondCp}cp`;
    }

    if (!ok) {
      if (i === 0) dropped = why;
      else notes.push(`trimmed at ${seed.line[i]}: ${why}`);
      break;
    }
    notes.push(`${seed.line[i]} ok (${why})`);
    solution.push(uci);
    fen = after;
    if (mates) break;
  }

  // A line must end on the player's move.
  while (solution.length && solution.length % 2 === 0) solution.pop();

  if (dropped || !solution.length) {
    report.push(`DROP ${seed.id} "${seed.title}": ${dropped || 'empty'}`);
    continue;
  }
  const san = [];
  let f = start;
  for (const move of solution) { san.push(sanFor(f, move)); f = applyUci(f, move).fen; }
  out.push({
    id: seed.id, mission: seed.mission, title: seed.title, hint: seed.hint,
    fen: start, sideToMove: start.split(' ')[1],
    solution, solutionSan: san, verifiedDepth: DEPTH
  });
  report.push(`ok   ${seed.id} "${seed.title}": ${san.join(' ')}   [${notes.join('; ')}]`);
}

engine.dispose?.();

const body = `/**
 * puzzles.js - GENERATED by tools/verify-puzzles.mjs. Do not edit by hand:
 * edit tools/puzzle-seeds.mjs and re-run the verifier.
 *
 * Every solution below was checked by Stockfish at depth ${DEPTH}: each player
 * move is the unique winning move (or an immediate mate), and each reply is
 * the engine's own best defence.
 */
export const PUZZLES = ${JSON.stringify(out, null, 2)};

export const puzzlesForMission = (missionId) => PUZZLES.filter((p) => p.mission === missionId);

export default PUZZLES;
`;
await writeFile(new URL('../js/data/puzzles.js', import.meta.url), body);
console.log(report.join('\n'));
console.log(`\n${out.length}/${PUZZLE_SEEDS.length} puzzles verified -> js/data/puzzles.js`);
process.exit(0);
